### ISSUE TITLE
Missing thinCapacityAllocatedInKm in Statistics struct

### ISSUE THREAD

**Issue by redsux** [emccode/goscaleio#30]
Hi,

I tried to use your library but it miss at least one useful metric : 
`` ThinCapacityAllocatedInKb                    int `json:"thinCapacityAllocatedInKm"` ``

When EMC will fix the typo issue it should end with "Kb" instead "Km".

Do you need a PR ?

Regards,

**Comment by codenrhoden** [comment]
Hi @redsux !

PRs are definitely welcome! Can you link to the line in the code where you've found a typo? I've looked around, and cannot find it myself. I also cannot find a `thinCapacityAllocatedInKb` field described at all in the ScaleIO Gateway API docs. It's possible I'm looking at old docs...

And now I just looked at Rev 02 of the ScaleIO User Guide for 2.0.x, and see what you are talking about. `thinCapacityAllocatedInKm` is actually in the docs. I'd have to do a bit of testing and see what is actually coming back from the Gateway, and we could definitely add that field into the struct so that you can pull it out. Good catch!  Thank you, and again, a PR is most certainly welcome as well.

**Comment by redsux** [comment]
Hi @codenrhoden ,

Sorry for the delay, i'll fork and prepare a PR !
This is a funny typo mistake, a capacity in Kilometer 😆

Regards,

**Comment by codenrhoden** [comment]
This repo is no longer maintained and I am closing out issues before archiving it.

The project is now maintained by Dell at https://github.com/dell/goscaleio
